Update dependencies to support ESLint8
The `jest` dependency was updated because tests could not be run after
upgrading the eslint dependencies. I had the following error:

```
TypeError: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'http://localhost/eslintrc.cjs'

      at Function.createRequire (node_modules/jest-runtime/build/index.js:1418:23)
      at Object.<anonymous> (node_modules/@eslint/eslintrc/lib/config-array-factory.js:57:17)
      at Object.<anonymous> (node_modules/eslint/lib/cli-engine/cli-engine.js:33:5)
```